Change rbenv and ruby references to lua

diff --git a/libexec/luaenv b/libexec/luaenv
--- a/libexec/luaenv
+++ b/libexec/luaenv
@@ -3,11 +3,11 @@ set -e
 export -n CDPATH
 
 if [ "$1" = "--debug" ]; then
-  export RBENV_DEBUG=1
+  export LUAENV_DEBUG=1
   shift
 fi
 
-if [ -n "$RBENV_DEBUG" ]; then
+if [ -n "$LUAENV_DEBUG" ]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
@@ -30,39 +30,39 @@ abs_dirname() {
   cd "$cwd"
 }
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${LUAENV_ROOT}" ]; then
+  LUAENV_ROOT="${HOME}/.luaenv"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  LUAENV_ROOT="${LUAENV_ROOT%/}"
 fi
-export RBENV_ROOT
+export LUAENV_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$(pwd)"
+if [ -z "${LUAENV_DIR}" ]; then
+  LUAENV_DIR="$(pwd)"
 else
-  cd "$RBENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+  cd "$LUAENV_DIR" 2>/dev/null || {
+    echo "luaenv: cannot change working directory to \`$LUAENV_DIR'"
     exit 1
   } >&2
-  RBENV_DIR="$(pwd)"
+  LUAENV_DIR="$(pwd)"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export LUAENV_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${LUAENV_ROOT}/plugins/"*/bin; do
   bin_path="${bin_path}:${plugin_bin}"
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${LUAENV_HOOK_PATH}:${LUAENV_ROOT}/luaenv.d:/usr/local/etc/luaenv.d:/etc/luaenv.d:/usr/lib/luaenv/hooks"
+for plugin_hook in "${LUAENV_ROOT}/plugins/"*/etc/luaenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
-export RBENV_HOOK_PATH="$hook_path"
+export LUAENV_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
 
@@ -70,15 +70,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(luaenv---version)\n$(luaenv-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec luaenv---version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "luaenv-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "luaenv: no such command \`$command'" >&2
     exit 1
   fi
 
diff --git a/libexec/luaenv-which b/libexec/luaenv-which
--- a/libexec/luaenv-which
+++ b/libexec/luaenv-which
@@ -2,17 +2,17 @@
 #
 # Summary: Display the full path to an executable
 #
-# Usage: rbenv which <command>
+# Usage: luaenv which <command>
 #
-# Displays the full path to the executable that rbenv will invoke when
+# Displays the full path to the executable that luaenv will invoke when
 # you run the given command.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$LUAENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide luaenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec luaenv shims --short
 fi
 
 expand_path() {
@@ -48,34 +48,34 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
-RBENV_COMMAND="$1"
+LUAENV_VERSION="$(luaenv-version-name)"
+LUAENV_COMMAND="$1"
 
-if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage which >&2
+if [ -z "$LUAENV_COMMAND" ]; then
+  luaenv-help --usage which >&2
   exit 1
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  PATH="$(remove_from_path "${RBENV_ROOT}/shims")"
-  RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND" || true)"
+if [ "$LUAENV_VERSION" = "system" ]; then
+  PATH="$(remove_from_path "${LUAENV_ROOT}/shims")"
+  LUAENV_COMMAND_PATH="$(command -v "$LUAENV_COMMAND" || true)"
 else
-  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
+  LUAENV_COMMAND_PATH="${LUAENV_ROOT}/versions/${LUAENV_VERSION}/bin/${LUAENV_COMMAND}"
 fi
 
-for script in $(rbenv-hooks which); do
+for script in $(luaenv-hooks which); do
   source "$script"
 done
 
-if [ -x "$RBENV_COMMAND_PATH" ]; then
-  echo "$RBENV_COMMAND_PATH"
+if [ -x "$LUAENV_COMMAND_PATH" ]; then
+  echo "$LUAENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "luaenv: $LUAENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
+  versions="$(luaenv-whence "$LUAENV_COMMAND" || true)"
   if [ -n "$versions" ]; then
     { echo
-      echo "The \`$1' command exists in these Ruby versions:"
+      echo "The \`$1' command exists in these Lua versions:"
       echo "$versions" | sed 's/^/  /g'
       echo
     } >&2
